version: '1'
services:
    postgresql:
        image: postgres:15
        container_name: postgres_db
        environment:
            POSTGRES_DB: airportdb
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
        ports:
            - "5435:5432"
        networks:
            - kafka-net
    zookeeper:
        image: confluentinc/cp-zookeeper:7.4.4    
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - "2181:2181"
        networks:
            - kafka-net
        healthcheck:
            test: ["CMD", "nc", "-z", "localhost", "2181"]
            interval: 10s
            retries: 3
            start_period: 20s
            timeout: 5s
    kafka:
        image: confluentinc/cp-kafka:7.4.4
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
        networks:
            - kafka-net

networks:
    kafka-net:
        driver: bridge
